### PR TITLE
Make sure sentinel implementation works

### PR DESCRIPTION
**Pull request by tsteur**
refs #23 

There are two fixes:
- When saving settings via UI we use the correct backend (Sentinel or Redis) to check connection works
- It should now actually ask sentinel for the current master server address

To use sentinel one must configure a new config setting now (`sentinel_master_name`)

### CODE REVIEW

**Comment by tsteur** [comment]
FYI: Sentinel should be configured via UI now and can accept multiple servers

**Comment by ChristianGfK** [comment]
Looks great so far!

One thing that stood out to me when I went to try it out:
All the sentinel-specific help texts on the plugin configuration page only show up after checking the sentinel checkbox **and then clicking save and thus reloading the page**. However, there's no indication that everything will look different once you do this.
Either forcing a save/reload right when checking the box, or at least indicating that you should click save right away after checking it, would make this more easily understandable.

Also, I guess trim()-ing the exploded hostnames/ports would probably be wise.
I bet there's going to people who will format the list as "host1, host2, host3", simply because that's the natural thing to do.

Apart from that, it seems like it's working just fine, right now. :+1:

**Comment by tsteur** [comment]
> All the sentinel-specific help texts on the plugin configuration page only show up after checking the sentinel checkbox and then clicking save and thus reloading the page

Unfortunately, the Piwik Settings API doesn't let us do such things so far. I will try to make the text a little bit more clear. 

> Also, I guess trim()-ing the exploded hostnames/ports would probably be wise.

The values should be trimmed already and there are tests for it see eg https://github.com/piwik/plugin-QueuedTracking/pull/39/files#diff-93972b6811cf61deea59203557827f2aR191 . Was it not working?

**Comment by ChristianGfK** [comment]
> The values should be trimmed already and there are tests for it see eg https://github.com/piwik/plugin-QueuedTracking/pull/39/files#diff-93972b6811cf61deea59203557827f2aR191 . Was it not working?
Never mind - I just tried looking for trim() in the code quickly and didn't see it. I didn't actually check then.
I did now and it seems to work just fine. Sorry for the confusion.

**Pull request merged**
