### PR TITLE
Use DI to setup test environment (for DI refactor in core)

### PR DESCRIPTION
**Pull request by diosmosis**
As title.

Refs #8027

### CODE REVIEW

**Comment by mattab** [comment]
from @diosmosis 

> The build won't pass, there's one failure left. I tried to fix it, but can't seem to figure out what the problem is.

@tsteur  could you take a look at this next week or so? (before 2.14.0 release)

**Comment by mattab** [comment]
I didn't realise but the main piwik is actually broken as a result. @tsteur your help will be much appreciated here :)

**Comment by tsteur** [comment]
I will have a look tmrw. I reckon this also requires a new Piwik version in `plugin.json`?

**Comment by mattab** [comment]
> I reckon this also requires a new Piwik version in plugin.json

didn't check, but it would make sense

**Comment by tsteur** [comment]
I can't run the tests so far they always fail because of problems with DI. Always getting 

```Piwik\Plugins\QueuedTracking\tests\Integration\Tracker\HandlerTest::test_process_ShouldDirectlyProcessQueueOnceNumRequestsPresent_IfEnabled
Argument 1 passed to Piwik\Plugins\QueuedTracking\Queue\Factory::makeBackendFromSettings() must be an instance of Piwik\Plugins\QueuedTracking\Settings, null given, called in /home/vagrant/www/piwik/plugins/QueuedTracking/Queue/Factory.php on line 26 and defined
```

**Comment by tsteur** [comment]
All tests run & succeed for me locally right now

**Pull request merged**
