### PR TITLE
Making sure that the uadata param is always a JSON string

### LINKED ISSUE #194: Tracking requests are stored but none are processed
I have QueuedTracking with Redis and using Memurai on a Windows machine. When plugin is active, I can see items in queue but none of them are processed. 

Exception from the matomo.log:
```
#0\core\Tracker\RequestSet.php(161),
#1\plugins\QueuedTracking\Queue.php(94),
#2\plugins\QueuedTracking\Queue\Processor.php(112),
#3\plugins\QueuedTracking\Commands\Process.php(86),
#4\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(257),
#5\vendor\symfony\console\Symfony\Component\Console\Application.php(874),
#6\vendor\symfony\console\Symfony\Component\Console\Application.php(195),
[internal function]: Symfony\Component\Console\Application->doRun(),
#8\core\Console.php(135),
#9\core\Access.php(670)
```

Have tried processing the queue using the "Process during tracking request" and manually via `/console queuedtracking:process`.

Example output when monitoring:
```
35 (19+16) request sets left in queue. 810.84K used memory (1020.51K peak). 0 workers active.
35 (19+16) request sets left in queue. 810.84K used memory (1020.51K peak). 0 workers active.
36 (19+17) request sets left in queue. 810.84K used memory (1020.51K peak). 0 workers active.
```

Output when processing manually:
```
Starting to process request sets, this can take a while

This worker finished queue processing with 0req/s (0 requests in 0.11 seconds)
```

I am using these versions:
PHP: 8.0
Matomo: 4.11.0
MariaDB: 10.5.9.0
Memurai: 3.1.4
PHPRedis: 5.3.7

Output from `/console queuedtracking:test`
```
Settings that will be used:
Backend: redis
NumQueueWorkers: 2
NumRequestsToProcess: 5
ProcessDuringTrackingRequest: 1
QueueEnabled: 1

Redis backend only settings (does not apply when using MySQL backend):
Host: *******
Port: 6379
Timeout: 0
Password:
Database: 0
UseSentinelBackend: 0
SentinelMasterName: mymaster

Version / stats:
PHP version: 8.0.0
Uname: Windows NT DMZWA02 10.0 build 17763 (Windows Server 2016) AMD64
PHPRedis version: 5.3.7
Backend version: 6.2.6
Memory: array (
  'used_memory' => 914360,
  'used_memory_human' => '892.93K',
  'used_memory_rss' => 856472,
  'used_memory_rss_human' => '836.40K',
  'used_memory_peak' => 1045000,
  'used_memory_peak_human' => '1020.51K',
  'used_memory_peak_perc' => '87.50%',
  'used_memory_overhead' => 850600,
  'used_memory_startup' => 685912,
  'used_memory_dataset' => 63760,
  'used_memory_dataset_perc' => '27.91%',
  'allocator_allocated' => 957376,
  'allocator_active' => 1486848,
  'allocator_resident' => 818584,
  'total_system_memory' => 0,
  'total_system_memory_human' => '0B',
  'used_memory_lua' => 37888,
  'used_memory_lua_human' => '37.00K',
  'used_memory_scripts' => 416,
  'used_memory_scripts_human' => '416B',
  'number_of_cached_scripts' => 2,
  'maxmemory' => 0,
  'maxmemory_human' => '0B',
  'maxmemory_policy' => 'noeviction',
  'allocator_frag_ratio' => 1.55,
  'allocator_frag_bytes' => 529472,
  'allocator_rss_ratio' => 0.55,
  'allocator_rss_bytes' => -668264,
  'rss_overhead_ratio' => 1.05,
  'rss_overhead_bytes' => 37888,
  'mem_fragmentation_ratio' => 1.0,
  'mem_fragmentation_bytes' => 0,
  'mem_not_counted_for_evict' => 0,
  'mem_replication_backlog' => 0,
  'mem_clients_slaves' => 0,
  'mem_clients_normal' => 164128,
  'mem_aof_buffer' => 0,
  'mem_allocator' => 'jemalloc-3.6.0',
  'active_defrag_running' => 0,
  'lazyfree_pending_objects' => 0,
  'lazyfreed_objects' => 0,
)
MaxMemory Eviction Policy config: noeviction
MaxMemory config: 0

Performing some tests:
Redis is connected: 1
Connection works in general
Success for method set(testKey, value)
Success for method setnx(testnxkey, value)
Success for method setex(testexkey, 5, value)
Success for method set(testKeyWithNx, value, array (0 => 'nx',))
Success for method set(testKeyWithEx, value, array ('ex' => 5,))
Initial expire seems to be set correctly
setIfNotExists works fine
expireIfKeyHasValue seems to work fine
Extending expire seems to be set correctly
expireIfKeyHasValue correctly expires only when the value is correct
Expire is still set which is correct
deleteIfKeyHasValue seems to work fine
List feature seems to work fine
```

### PR DESCRIPTION
**Pull request by snake14**
### Description:

We have at least one customer which has the uadata param getting decoded earlier than it's supposed to and it's causing problems with the core tracker processing.
Fixes: #194 

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by AltamashShaikh — COMMENTED** [review]
@snake14 Changes looks good to me, I have asked for Stefan's review too and we can merge based on his comment

**Comment by sgiehl** [comment]
Generally this looks fine. But the question remains: Why should the json_decode also decode the uadata parameter. As it should be a string value within the url, it should normally not be decoded. Otherwise this could mean that any parameter containing values that look json_encoded, might result in a broken request.

**Comment by snake14** [comment]
> Generally this looks fine. But the question remains: Why should the json_decode also decode the uadata parameter. As it should be a string value within the url, it should normally not be decoded. Otherwise this could mean that any parameter containing values that look json_encoded, might result in a broken request.

@sgiehl That's true, but I haven't been able to reproduce the issue and there haven't really been any recent changes to this plugin. So, I'm not sure where to look.

**Comment by snake14** [comment]
I tried again to reproduce the issue and was unable to. It looks like the customers were using Redis 6 and I used Redis 7, but I don't think that would be the issue. Should we just merge this so that it will be released next week @AltamashShaikh ?

**Comment by AltamashShaikh** [comment]
@snake14 I have redis 5.0.7 and the uadata is always `{}` so unlikely its a redis version issue and I couldn't find anything in code where we would be converting it to array. The fix does solve the problem for users, so I would say merge it

**Pull request merged**
