### PR TITLE
Multi Tenant suggestion

### PR DESCRIPTION
**Pull request by volp1s**
This is a suggestion Multi Tenant.
I'm working with a multi tenant setup as described [here](https://developer.matomo.org/guides/multi-tenants) in the Matomo documentation. The documentation describes how split the mysql database.
Having multiple redis-server as backends can be complicated instead.
It could be possibile to use multiple databases in redis, but performance can become awful when period flush to disk is active.
Adding a suffix to the list key with the Matomo hostname picked from the $trusted_hosts config variable can be a solution, avoiding conflicts across instances.

### CODE REVIEW

**Comment by snake14** [comment]
@AltamashShaikh Do you know why this PR was never merged? Did we simply not notice that it had been created? Do you see a reason not to merge this or should we wait till after Matomo 5.0.0?

**Comment by AltamashShaikh** [comment]
@snake14 Dunno why this was never merged, I think we missed it and just adding braces with if is my suggestion to this PR

**Comment by AltamashShaikh** [comment]
@snake14 This would require migration too right ?
Since we updated the key

**Comment by snake14** [comment]
> @snake14 This would require migration too right ? Since we updated the key

Good call @AltamashShaikh . Since it would be looking for a different key, we would probably want a migration for existing installations. I'll mark this PR for needing to be moved to 5.x.

**Pull request closed without merging**
