### PR TITLE
Send email notification when queue reaches a certain size

### LINKED ISSUE #71: Send email notification when queue is large
If something goes wrong with the queued tracking or for some reason the processing part isn't fast enough to keep up with processing the queue, we may want to send email notifications for example max once per hour. 

Could send an email to a configured list of emails (not super users in this case), for example when > 500K entries are in queue, when > 1.5 Mio entries are in queue, when > 5 mio entries are in queue or so. Max once per hour, unless an even higher threshold is crossed.

### PR DESCRIPTION
**Pull request by tsteur**
fixes #71

Could also add translation keys for the email but think not needed as sent from CLI anyway etc.

Also noticed `uninstall` was missing but it would currently not uninstall any `queue list` if a MySQL backend is used... need to create a bug for this. (#73)

### CODE REVIEW

**Comment by tsteur** [comment]
cc @mattab 

kept it simple but useful!

**Comment by diosmosis** [comment]
Code looks good, build is failing here: https://travis-ci.org/matomo-org/plugin-QueuedTracking/jobs/366338040 due to `DEFAULT_NOTIFY_EMAILS` value being an array. Will be able to test locally Sunday.

**Comment by tsteur** [comment]
Ouch yeah... I'll fix it tomorrow.

**Comment by tsteur** [comment]
test fixed

**Comment by tsteur** [comment]
image

done

**Pull request merged**
