### PR TITLE
use credis version 1.11.1

### LINKED ISSUE #123: Incomtabile with PHP 7.4
When running on PHP 7.4.2 I get this:
```
Processor will start once there are at least 5 request sets in the queue
WARNING [2020-02-24 09:03:20] 50  /var/www/html/plugins/QueuedTracking/libs/credis/Client.php(1249): Deprecated - implode(): Passing glue string after array is deprecated. Swap the parameters - Matomo 3.13.3 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)
2 (2) request sets left in queue. 2.01M used memory (2.40M peak). 0 workers active.        Error: error or warning logs detected, exit 1
2020-02-24 09:03:20,310 INFO exited: queuedtracking-monitor_00 (exit status 0; not expected)
2020-02-24 09:03:42,349 INFO spawned: 'queuedtracking-monitor_00' with pid 51
```

### PR DESCRIPTION
**Pull request by sgiehl**
fixes #123

### CODE REVIEW

**Comment by tsteur** [comment]
@sgiehl I don't have redis installed currently and can't really test it. Which version was used before that? Be great to check in their changelog if there were any changes that could be relevant.

**Comment by sgiehl** [comment]
I guess it was version 1.7.0. As 1.8.0 already required PHP 5.4 in composer.json.
So there were quite a few changes: https://github.com/colinmollenhour/credis/compare/1.7...1.11.1

**Comment by tsteur** [comment]
@sgiehl just installed redis and sentinel

redis server
image

redis sentinel
image

redis sentinel config

```
sentinel myid 0f7b0b5662f728c627c363cfa4f49fcf49013504
sentinel deny-scripts-reconfig yes
sentinel monitor mymaster 127.0.0.1 6379 2
sentinel down-after-milliseconds mymaster 60000
# Generated by CONFIG REWRITE
port 26379
dir "path to my matomo install where I'm running it"
protected-mode no
sentinel config-epoch mymaster 0
sentinel leader-epoch mymaster 0
sentinel current-epoch 0
```

All the tests always fail with a timeout  on PHP 7.4. 
After lot of debugging and thinking config is wrong noticed it fails because of a timeout.
Had to change the timeout from `0.5` to `1` to make the tests work for me.
image

Thought maybe something changed but the docs say `float $timeout  Timeout period in seconds`. So tested hard configured 0.9, 0.5 and it still worked. Then realised the `$timeout` variable is `0.5` but `$this->timeout` is `0.0`:

image

So this might be somehow some regression?

Our default timeout is set to `0.0` so this could affect some people?

image

I don't know if this is a change in PHP, redis server, or credis. It looks like it might use `stream_socket_client()` if the `Redis` extension isn't installed. I used to have this extension installed so maybe that's the problem. 

For redis extension I do see a default timeout of `0.0` and not sure what it means?

image


I guess it might be fine to install but ideally, when Sentinel is used, and the `Redis` extension is not available, maybe we should change a value of `0.0` to `0.01`?

Like 
image
Not sure if there was any trick in PHP to comparing floats. Forgot...

**Comment by tsteur** [comment]
Wonder if it makes sense to also change default value in the settings if `Redis` class is not available say to `0.1` or so

**Comment by mattab** [comment]
> I guess it might be fine to install but ideally, when Sentinel is used, and the Redis extension is not available, maybe we should change a value of 0.0 to 0.01?

That'd be great to try, if there's a chance it helps with sentinel

**Comment by sgiehl** [comment]
@tsteur I have actually neither Redis nor Sential installed atm. I've only created the PR based on the reported incompatibility with PHP 7.4. I can for sure install redis and have a look if you think it's worth the time. Otherwise feel free to push the suggested changes by yourself. Maybe someone else is able to test it then?

**Comment by tsteur** [comment]
@sgiehl done the change that should work. 

@mikkeschiren could you give this a test? Here's the zip: https://github.com/matomo-org/plugin-QueuedTracking/archive/credisupdate.zip

**Comment by kfogle** [comment]
Can we expect this to be merged anytime soon?

**Comment by tsteur** [comment]
@kfogle as mentioned in previous comment we'd need someone to confirm this works. I'd be happy to merge then

**Comment by kfogle** [comment]
I've copied the zip mentioned above and deployed it out to a dev environment. I can confirm the deprecation warning went away and the plugin was functional.

**Pull request merged**
